import { VibeOption, WorkoutRoutine, VibeStage, ExerciseFormGuide } from '../types';

export const DEFAULT_FORM_GUIDE: ExerciseFormGuide = {
  gripSetup: 'Neutral overhand grip shoulder-width apart.',
  bodyAlignment: 'Hollow body hold with tight core and glutes.',
  execution: 'Control movement smoothly through full range of motion.',
  commonMistakes: ['Flaring elbows out to 90 degrees.', 'Using momentum or kipping.'],
  proTips: 'Maintain maximum muscular tension throughout every rep.',
  animatedCue: 'Controlled vertical movement trajectory.',
};

export const VIBE_OPTIONS: VibeOption[] = [
  {
    stage: 1,
    id: 'Restorative',
    title: 'Restorative',
    subtitle: 'Zen Recovery',
    description: 'Gentle joint mobility & spinal decompression.',
    numberLabel: '01',
    estimatedMins: 20,
    estimatedCalories: 110,
    badge: 'Gentle Recovery',
  },
  {
    stage: 2,
    id: 'Steady Flow',
    title: 'Steady Flow',
    subtitle: 'Zone 2 Cardio',
    description: 'Rhythmic functional strength & posture endurance.',
    numberLabel: '02',
    estimatedMins: 35,
    estimatedCalories: 240,
    badge: 'Endurance & Posture',
  },
  {
    stage: 3,
    id: 'High Energy',
    title: 'High Energy',
    subtitle: 'Muscle Sculpt',
    description: 'Targeted progressive muscle building & hypertrophy.',
    numberLabel: '03',
    estimatedMins: 50,
    estimatedCalories: 420,
    badge: 'Muscle Building',
  },
  {
    stage: 4,
    id: 'Peak Power',
    title: 'Peak Power',
    subtitle: 'Primal Heavy',
    description: 'Heavy compound lifts & explosive PR attempts.',
    numberLabel: '04',
    estimatedMins: 60,
    estimatedCalories: 580,
    badge: 'Heavy PR Lifts',
  },
];

export const ROUTINES_MAP: Record<VibeStage, WorkoutRoutine> = {
  Restorative: {
    id: 'restorative-01',
    vibeStage: 'Restorative',
    title: 'Zen Recovery & Spine Decompression',
    description: 'Low-impact flow designed for joint health and deep recovery.',
    estimatedMins: 20,
    estimatedCalories: 110,
    exercises: [
      {
        id: 'r1',
        name: 'Cat-Cow Spine Flow',
        category: 'Mobility',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Spine', 'Core'],
        recommendedSets: 3,
        recommendedReps: '12 reps',
        ghostPerformance: { lastReps: 12, lastWeightKg: 0, lastDate: '3 days ago' },
      },
      {
        id: 'r2',
        name: 'World\'s Greatest Stretch',
        category: 'Flexibility',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Hips', 'Thoracic Spine'],
        recommendedSets: 3,
        recommendedReps: '8 reps / side',
        ghostPerformance: { lastReps: 8, lastWeightKg: 0, lastDate: '3 days ago' },
      },
      {
        id: 'r3',
        name: 'Child\'s Pose Deep Breathing',
        category: 'Decompression',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Lats', 'Lower Back'],
        recommendedSets: 3,
        recommendedReps: '60s hold',
        ghostPerformance: { lastReps: 60, lastWeightKg: 0, lastDate: '3 days ago' },
      },
    ],
  },
  'Steady Flow': {
    id: 'steady-01',
    vibeStage: 'Steady Flow',
    title: 'Balanced Athletic Strength',
    description: 'Controlled tempo strength exercises for posture and stamina.',
    estimatedMins: 35,
    estimatedCalories: 240,
    exercises: [
      {
        id: 's1',
        name: 'Goblet Squat to Press',
        category: 'Full Body',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Quads', 'Glutes', 'Shoulders'],
        recommendedSets: 3,
        recommendedReps: '12 reps',
        suggestedWeightKg: 16,
        ghostPerformance: { lastReps: 12, lastWeightKg: 14, lastDate: 'Last week' },
      },
      {
        id: 's2',
        name: 'Single-Arm Dumbbell Row',
        category: 'Pull',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Lats', 'Upper Back'],
        recommendedSets: 3,
        recommendedReps: '12 reps / side',
        suggestedWeightKg: 18,
        ghostPerformance: { lastReps: 10, lastWeightKg: 18, lastDate: 'Last week' },
      },
      {
        id: 's3',
        name: 'Kettlebell Romanian Deadlift',
        category: 'Posterior',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Hamstrings', 'Glutes'],
        recommendedSets: 3,
        recommendedReps: '12 reps',
        suggestedWeightKg: 24,
        ghostPerformance: { lastReps: 12, lastWeightKg: 20, lastDate: 'Last week' },
      },
    ],
  },
  'High Energy': {
    id: 'high-01',
    vibeStage: 'High Energy',
    title: 'Hypertrophy & Posture Sculpt',
    description: 'Moderate-to-heavy resistance targeting major muscle groups.',
    estimatedMins: 50,
    estimatedCalories: 420,
    exercises: [
      {
        id: 'h1',
        name: 'Incline Dumbbell Chest Press',
        category: 'Push',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Upper Chest', 'Triceps'],
        recommendedSets: 4,
        recommendedReps: '10 reps',
        suggestedWeightKg: 26,
        ghostPerformance: { lastReps: 10, lastWeightKg: 24, lastDate: '4 days ago' },
      },
      {
        id: 'h2',
        name: 'Bulgarian Split Squat',
        category: 'Legs',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Quads', 'Glutes'],
        recommendedSets: 3,
        recommendedReps: '10 reps / leg',
        suggestedWeightKg: 16,
        ghostPerformance: { lastReps: 8, lastWeightKg: 16, lastDate: '4 days ago' },
      },
      {
        id: 'h3',
        name: 'Lat Pulldown / Pull-ups',
        category: 'Pull',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Lats', 'Biceps'],
        recommendedSets: 4,
        recommendedReps: '10 reps',
        suggestedWeightKg: 65,
        ghostPerformance: { lastReps: 10, lastWeightKg: 60, lastDate: '4 days ago' },
      },
    ],
  },
  'Peak Power': {
    id: 'peak-01',
    vibeStage: 'Peak Power',
    title: 'Heavy Compound Strength & Explosive PRs',
    description: 'Heavy resistance training focusing on max neurological output.',
    estimatedMins: 60,
    estimatedCalories: 580,
    exercises: [
      {
        id: 'p1',
        name: 'Barbell Back Squat',
        category: 'Legs',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Quads', 'Glutes', 'Core'],
        recommendedSets: 5,
        recommendedReps: '5 reps',
        suggestedWeightKg: 100,
        ghostPerformance: { lastReps: 5, lastWeightKg: 95, lastDate: '5 days ago' },
      },
      {
        id: 'p2',
        name: 'Barbell Flat Bench Press',
        category: 'Push',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Chest', 'Triceps'],
        recommendedSets: 5,
        recommendedReps: '5 reps',
        suggestedWeightKg: 85,
        ghostPerformance: { lastReps: 5, lastWeightKg: 80, lastDate: '5 days ago' },
      },
      {
        id: 'p3',
        name: 'Conventional Barbell Deadlift',
        category: 'Posterior',
        equipmentRequired: 'Home',
        formGuide: DEFAULT_FORM_GUIDE,
        targetMuscles: ['Hamstrings', 'Lower Back'],
        recommendedSets: 4,
        recommendedReps: '5 reps',
        suggestedWeightKg: 130,
        ghostPerformance: { lastReps: 5, lastWeightKg: 125, lastDate: '5 days ago' },
      },
    ],
  },
};
